### ISSUE TITLE
Out of place usage

### ISSUE THREAD

**Issue by SirKoriban** [elebumm/FlipACoinForMe#2]
https://www.reddit.com/r/leagueoflegends/comments/4p027e/riot_pls_dev_priorities_and_the_league_client/d4h1lmp

Just reporting that this coinflip was wrong to happen. Nowhere did he mention heads or tails, he simply only mentioned "one side of the coin" but in this context, the coin flip is just wrong/out of place.

Created an account just to let you know =)

**Comment by elebumm** [comment]
Thank you! I am working on ways to get this to work more efficiently.

**Comment by JamesCullum** [comment]
Same for https://www.reddit.com/r/Monero/comments/4ozr3w/maam_21_monero_ask_anything_monday/d4h31o6

Triggering at the Word "Coin" in a Bitcoin / Altcoin Subreddit is quite useless...

**Comment by elebumm** [comment]
Correct. I am currently working on this. Thanks for the feedback :)

**Comment by elebumm** [comment]
This has been fixed in current commit!
